### PR TITLE
Remove @@

### PR DESCRIPTION
**Pull request by thiagotalma**
@dmeroff , what was your intention with this format?

### CODE REVIEW

**Comment by dmeroff** [comment]
Thank you! That's not my idea with this format. It is the way how yii message command works. It encloses not used anymore messages in `@@`.

**Comment by thiagotalma** [comment]
But these strings are being used, right?

**Comment by dmeroff** [comment]
It seems that they are. And I don't know how they became enclosed in `@@`. Maybe some problem with message command.

**Comment by thiagotalma** [comment]
:+1:

**Pull request merged**
