### PR TITLE
redirect to home after registration

### PR DESCRIPTION
**Pull request by jspaine**
User was left logged in on a page with only flash message after registration/confirmation. Added redirect to home page.

Means the app has to display the registration complete flash message though.

### CODE REVIEW

**Comment by dmeroff** [comment]
I think this is application-specific change, so I don't think this should be merged. BTW this can be added as a guide or how-to to documentation, and you're very welcome to send such PR.

**Comment by arjenmeijer** [comment]
I do not think it is application specific. I do have the same problem. User are asking what to do after registration. So showing the home menu, is the correct solution for everybody, I think.

**Comment by xerxes87** [comment]
I agree.

**Comment by dmeroff** [comment]
`User are asking what to do after registration.`
What does this mean? Module shows flash message that says that confirmation link is sent, click link etc. What do you mean under home menu? It is really application-wide IMHO.

**Comment by arjenmeijer** [comment]
The user stays at the confirmation page. That is useless. I did already confirm my email address! So another page as to be shown.  The homepage is the entry point for the user, so that is the logical place to go.

**Pull request closed without merging**
