### PR TITLE
fix User::isAdmin to check admin access for model user instead of Yii::$app->user

### PR DESCRIPTION
**Pull request by Vediovis**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Fixed issues  | no

### CODE REVIEW

**Comment by thiagotalma** [comment]
What is the problem that this PR solves?

**Comment by bscheshirwork** [comment]
I think this PR about this case:

```php
$loggedUser = \Yii::$app->user->identity;
$loggedUser->isAdmin;
$anotherUser = \dektrium\user\models\User::findOne(100500);
$anotherUser->isAdmin;
```

**Comment by thiagotalma** [comment]
Merged by https://github.com/dektrium/yii2-user/commit/b7180b29f3f0673b4ee5f19f5974cc2e95b93cd6

**Comment by schmunk42** [comment]
I (just) support we're an admin here
```
$loggedUser = \Yii::$app->user->identity;
echo $loggedUser->isAdmin;
```

So this would print `1`.


I suppose `100500` is not an admin
```
$anotherUser = \dektrium\user\models\User::findOne(100500);
//incorrect check $loggedUser instead anotherUser
echo $anotherUser->isAdmin; // \Yii::$app->user->can($this->module->adminPermission) : false) 
```
This would still print `1`?

@bscheshirwork 
So yes, now as I've written about it, I understand the issue :nerd_face: nice catch, thank you!

**Pull request closed without merging**
