### PR TITLE
Named rules

### PR DESCRIPTION
**Pull request by thiagotalma**
With the named rules, we have more freedom to work them when overriding the model.

For example, overwriting only the usernameLength rule.

### CODE REVIEW

**Comment by dmeroff** [comment]
Good idea! I've already thought about something like this, bud I haven't implemented it.
Could you please do the same thing with other models?

**Comment by thiagotalma** [comment]
@dmeroff Done!
 separated a few rules in order to be handled individually.

**Comment by dmeroff** [comment]
You've done awesome job! Thanks! I've done some comments, please fix them and I'll merge this!

**Comment by thiagotalma** [comment]
Done!

**Comment by dmeroff** [comment]
Thank you!

**Pull request merged**
