### PR TITLE
Feature admin needs to activate new users

### PR DESCRIPTION
**Pull request by jkmssoft**
This PR adds a new configuraton attribute "enableActivationByAdminIsRequired".
If it is set to true new users need to get activated by an administrator before they can log in.

activateuser

| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Fixed issues | #629 |

### CODE REVIEW

**Comment by Webkadabra** [comment]
Please, accept this one :)

**Comment by thyseus** [comment]
+1 for this feature, but i think 'enableActivationByAdminIsRequired' is badly named.
I propose to name it 'activationByAdmin' which is shorter and simpler but self-explaining.

**Comment by jkmssoft** [comment]
What about `enableActivationByAdmin`?
Any other suggestions?

**Comment by dmeroff** [comment]
Thank you for your contribution, but this PR will not be merged because of [this](https://github.com/dektrium/yii2-user/issues/629#issuecomment-270945609).

**Pull request closed without merging**
