### PR TITLE
recovery with wrong email return success status

### PR DESCRIPTION
**Pull request by odyswise**
I have some requests from users - they tryed to recovery user with wrong letter capitalization in email (PostgreSQL do not find them). Users saw success flash and wait mails. But no mail was send)

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by odyswise** [comment]
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

**Comment by billychow** [comment]
I just found this issue during unit testing.
Waiting for being merged to master branch.

**Comment by thiagotalma** [comment]
@odyswise please open a new PR for travis.

**Comment by thiagotalma** [comment]
lets discuss here: https://github.com/dektrium/yii2-user/pull/942

**Pull request closed without merging**
