### PR TITLE
Link to sign up on login screen

### PR DESCRIPTION
**Pull request by thiagotalma**
Hello!

What do you think of including on the login screen a link to the user who does not have registration sign up?

### CODE REVIEW

**Comment by dmeroff** [comment]
Good idea, thanks. Fix the line which I've commented and I'll merge this.

**Comment by thiagotalma** [comment]
Excuse me!
Fixed!

**Comment by thiagotalma** [comment]
See, is showing the repeated message.
Note that one can be closed and the other not. It was probably a problem with the included flash messages.
http://i.imgur.com/deBC9PS.png

**Comment by dmeroff** [comment]
Thank you!

If you have custom widget which shows flash messages (like included one in advanced template), then you should turn off `enableFlashMessages` property of module.

**Pull request merged**
