### PR TITLE
Including the tests into the app tests

### PR DESCRIPTION
**Pull request by yurigo79**
Now you can include the test in the codeception.yml file by 
```yaml
include:
  - ../vendor/dektrium/yii2-user/tests/
```

### CODE REVIEW

**Comment by yurigo79** [comment]
fixing a Yii namespace aware calling in the tests

**Comment by dmeroff** [comment]
Is there real need in having namespaces inside the functional tests? As I can see in codeception docs, it isn't needed. Could you please fix this, and also fix issues I mentioned in your code.

**Comment by yurigo79** [comment]
without a namespace you can't include the test in the application tests.
and without a namespace defined in the all classes the test are being failed.

**Comment by dmeroff** [comment]
Tests are failed without a namespace, because you're not importing FunctionaTester class. I think we shouldn't declare namespace there, so we just should import `dektrium\user\tests\FunctionalTester` there:

E.g. `ConfirmationCept.php`:

```php
use dektrium\user\tests\FunctionalTester; // <=== here we import FunctionalTester instead of defining namespace 
use yii\helpers\Url;

$I = new FunctionalTester($scenario);
....
```

**Comment by yurigo79** [comment]
Ok
fixed it

**Comment by dmeroff** [comment]
Thank you!

**Pull request merged**
