### PR TITLE
change php 7.2 special word Class to BaseClass

### PR DESCRIPTION
**Pull request by bscheshirwork**
@thyseus 
@thiagotalma
@dmeroff

please check it!
Merge and create tags 
as fast as possible ^^

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no/yes
| Fixed issues  | #992

### CODE REVIEW

**Comment by marty-macfly** [comment]
If, I'm not mistaken, I think you should also update composer.json because BaseObject is available only from Yii 2.0.13, so it will not work with older version.

**Comment by bscheshirwork** [comment]
@marty-macfly you right. We can see for time of creation BaseObject

**Comment by bscheshirwork** [comment]
So. We need versioned yii2-user. 
Current-tag version work with `php 7.1.11`
next-tag version work with `php 7.2.0` and require `yii 2.0.13`

**Comment by thiagotalma** [comment]
Merged.
Thanks!

**Pull request merged**
