### PR TITLE
Widgetized the user menu.

### PR DESCRIPTION
**Pull request by derekisbusy**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by derekisbusy** [comment]
Widgetized the user menu so that menu items can be added by other extensions.

**Comment by davidnewcomb** [comment]
This is just what I was looking for, how did you know?
Your commit, so far, has not been merged into master yet so I ended up using the [Overriding Views](https://github.com/dektrium/yii2-user/blob/master/docs/overriding-views.md) feature of yii2-user to use my own `_menu.php`.
I think your change is a better way of modifying the profile navigation bar as we will still be able to take changes to the original view without having to keep track of them yourself.

**Comment by derekisbusy** [comment]
You can also change your composer.json to use my branch by adding the following to the repositories section:

```json

"repositories":[
    {
        "type": "vcs",
        "url": "https://github.com/derekisbusy/yii2-user-1.git"
    }
]

```

And changing the require line to:

```json
        "dektrium/yii2-user": "dev-menu",
```

Then change back if the pull request is merged.

**Comment by davidnewcomb** [comment]
Ok, done. I'm having a bit of trouble actually adding to the `$items` without updating (or overriding) all the views and controllers. What's the simplest way of doing it?

**Comment by thiagotalma** [comment]
Thanks!

**Comment by davidnewcomb** [comment]
Now that the menu has been widgetized, how/where are you supposed to add the extra menu items to UserMenu?
The UserMenu widget is still hard coded into the view so adding extra items will be overridden when UserMenu::init is called.
Was the point to allow the users to override the whole of UserMenu (in Overriding Views style) or are we supposed to be able to add extra menu items somewhere?

**Pull request merged**
