### PR TITLE
Use getters instead of references to dependencies.

### PR DESCRIPTION
**Pull request by SamMousa**
This uses getters for the protected properties in the User model.

This is an improvement to the current implementation, but still it is not an ideal way of dependency injection.

### CODE REVIEW

**Comment by dmeroff** [comment]
At the moment tests are broken. I've added some comments on changes you made, could you please fix them? Also could you please do the same refactoring with other active record model to make them more consistent?

**Comment by SamMousa** [comment]
Will do, this week!

**Comment by SamMousa** [comment]
I find it difficult to get the tests running properly.
1. The behavior to include autoload.php is not really user friendly.
-- I've changed it to traverse the directory tree until it finds a proper file. (Since performance is irrelevant here, and usability is more important)
2. Codeception itself is not part of the require-dev part of composer.json.
3. The tests seem to depend on the database being initialized, but there are no SQL files or scripts that actually initialize the DB to a known state...

**Comment by dmeroff** [comment]
1. Ok, that's nice
2. Yes, but I prefer installing codeception globally rather than installing it as a dependency for each project.
3. To initialize testing db you can just use migrations (test app uses `dektrium_test` table as a default)

Moreover you can take a look at [.travis.yml](https://github.com/dektrium/yii2-user/blob/master/.travis.yml) file which is used to set up tests on travis ci.

At the moment tests are still broken.

**Comment by SamMousa** [comment]
@dmeroff Finally got codeception running.
-- Why can't codeception do the database setup?

Anyway, tests should (mostly) pass now!

**Comment by dmeroff** [comment]
Thank you!
I want to refactor tests (move them to codeception 2.1) which will help to setup and run test. I hope I can do this as soon as possible.

**Pull request merged**
